FROM nmch/docker-apache-php:php73

RUN yum install -y php-pecl-xdebug \
	&& yum install -y php-phpunit-* \
	&& yum install -y net-tools iproute \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& yarn global add apidoc \
	&& wget -q https://github.com/phpDocumentor/phpDocumentor/releases/download/v2.9.1/phpDocumentor.phar -O /usr/local/bin/phpDocumentor \
	&& chmod 755 /usr/local/bin/phpDocumentor
