name: docker-apache-php

on: [ "push", "workflow_dispatch" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.GITHUB_REPOSITORY }}:${{ steps.extract_branch.outputs.branch }}
