name: docker-apache-php

on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: docker build . -t ${GITHUB_REPOSITORY}:${{ steps.extract_branch.outputs.branch }}
      - run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin
      - run: docker push ${GITHUB_REPOSITORY}:${{ steps.extract_branch.outputs.branch }}
      - run: docker build . -t ${GITHUB_REPOSITORY}:${{ steps.extract_branch.outputs.branch }}-dev
      - run: docker push ${GITHUB_REPOSITORY}:${{ steps.extract_branch.outputs.branch }}-dev
