name: docker-apache-php

on: [ "push", "workflow_dispatch" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - run: docker build . -t ${GITHUB_REPOSITORY}:${BRANCH}
      - run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin
      - run: docker push ${GITHUB_REPOSITORY}:${BRANCH}
      - run: docker tag ${GITHUB_REPOSITORY}:${BRANCH} ${GITHUB_REPOSITORY}:${BRANCH}-${GITHUB_RUN_NUMBER}
      - run: docker push ${GITHUB_REPOSITORY}:${BRANCH}-${GITHUB_RUN_NUMBER}
      - run: docker build . -t ${GITHUB_REPOSITORY}:${BRANCH}-dev -f Dockerfile-dev
      - run: docker push ${GITHUB_REPOSITORY}:${BRANCH}-dev
      - run: docker tag ${GITHUB_REPOSITORY}:${BRANCH}-dev ${GITHUB_REPOSITORY}:${BRANCH}-dev-${GITHUB_RUN_NUMBER}
      - run: docker push ${GITHUB_REPOSITORY}:${BRANCH}-dev-${GITHUB_RUN_NUMBER}
